checking in ghostty config and cleaning up nix app scripts

diff --git a/apps/darwin/copy-keys b/apps/darwin/copy-keys
--- a/apps/darwin/copy-keys
+++ b/apps/darwin/copy-keys
@@ -1,12 +1,22 @@
 #!/usr/bin/env bash
-set -e
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m'
+export SSH_DIR="$HOME"/.ssh
 
-username=${USER}
-export SSH_DIR=/Users/${username}/.ssh
+change_ownership() {
+	chown "${USER}":staff "${SSH_DIR}"/id_ed25519{,.pub}
+	chown "${USER}":staff "${SSH_DIR}"/id_ed25519_{agenix,agenix.pub}
+}
+
+copy_keys() {
+	if [ -n "${MOUNT_PATH}" ]; then
+		cp "${MOUNT_PATH}/id_ed25519_agenix.pub" "${SSH_DIR}"
+		cp "${MOUNT_PATH}/id_ed25519_agenix" "${SSH_DIR}"
+		chmod 600 "${SSH_DIR}"/id_ed25519_{agenix,agenix.pub}
+	else
+		echo -e "${RED}No USB drive found. Aborting.${NC}"
+		exit 1
+	fi
+}
 
 handle_no_usb() {
 	echo -e "${RED}No USB drive found or mounted.${NC}"
@@ -29,21 +39,6 @@ mount_usb() {
 	fi
 }
 
-copy_keys() {
-	if [ -n "${MOUNT_PATH}" ]; then
-		cp "${MOUNT_PATH}/id_ed25519_agenix.pub" "${SSH_DIR}"
-		cp "${MOUNT_PATH}/id_ed25519_agenix" "${SSH_DIR}"
-		chmod 600 "${SSH_DIR}"/id_ed25519_{agenix,agenix.pub}
-	else
-		echo -e "${RED}No USB drive found. Aborting.${NC}"
-		exit 1
-	fi
-}
-
-setup_ssh_directory() {
-	mkdir -p ${SSH_DIR}
-}
-
 set_keys() {
 	cp "${MOUNT_PATH}"/id_ed25519_github.pub "${SSH_DIR}"/id_ed25519.pub
 	cp "${MOUNT_PATH}"/id_ed25519_github "${SSH_DIR}"/id_ed25519
@@ -51,9 +46,8 @@ set_keys() {
 	chmod 644 "${SSH_DIR}"/id_ed25519.pub
 }
 
-change_ownership() {
-	chown "${username}":staff "${SSH_DIR}"/id_ed25519{,.pub}
-	chown "${username}":staff "${SSH_DIR}"/id_ed25519_{agenix,agenix.pub}
+setup_ssh_directory() {
+	mkdir -p "${SSH_DIR}"
 }
 
 setup_ssh_directory
